#pragma once

// GENERATED by Socket/scripts/sync-blocks.mts — do not edit.
// Source of truth: Socket/src/model/catalog.ts. Run `pnpm sync:blocks` in Socket.
//
// The contract between the interface and the DSP. Socket addresses a parameter
// as (block index, parameter index) and the engine's switch reads that index;
// nothing else keeps the two in step. A parameter inserted into the middle of a
// block would silently re-address every one after it, and you would hear it
// eventually as the wrong knob doing something.
//
// Every block in the catalogue gets a value here, including the ones with no
// engine yet. That way implementing one never renumbers the others.
//
// Parameter order, for writing setParam against:
//
//   osc: 0=Wave, 1=Tune, 2=Fine, 3=Level, 4=PW
//   sub: 0=Level, 1=Octave, 2=Shape
//   noise: 0=Kind, 1=Level, 2=Colour
//   wavetable: 0=Table, 1=Position, 2=Warp, 3=Level
//   sampler: 0=Start, 1=Length, 2=Tune, 3=Level, 4=Loop
//   fmop: 0=Ratio, 1=Index, 2=Feedback, 3=Level
//   string: 0=Pitch, 1=Damping, 2=Position, 3=Level
//   filter: 0=Mode, 1=Cutoff, 2=Reso, 3=Env, 4=Key
//   formant: 0=Vowel, 1=Morph, 2=Width, 3=Mix
//   comb: 0=Tune, 1=Feedback, 2=Mix
//   drive: 0=Drive, 1=Bias, 2=Tone, 3=Mix
//   fold: 0=Fold, 1=Symmetry, 2=Mix
//   crush: 0=Bits, 1=Rate, 2=Jitter, 3=Mix
//   eq: 0=Low, 1=Lo mid, 2=Hi mid, 3=High
//   gate: 0=Thresh, 1=Attack, 2=Hold, 3=Release
//   env: 0=A, 1=D, 2=S, 3=R, 4=Curve, 5=Vel
//   env2: 0=Delay, 1=A, 2=D, 3=S, 4=R, 5=Curve, 6=Amount
//   lfo: 0=Shape, 1=Rate, 2=Depth, 3=Sync
//   random: 0=Mode, 1=Rate, 2=Amount, 3=Smooth
//   follow: 0=Attack, 1=Release, 2=Gain
//   seq: 0=Rate, 1=Swing, 2=Gate, 3=Loop
//   arp: 0=Mode, 1=Rate, 2=Octaves, 3=Gate
//   keytrack: 0=Amount, 1=Centre, 2=Curve
//   delay: 0=Time, 1=Feedback, 2=Spread, 3=Tone, 4=Mix, 5=Sync
//   reverb: 0=Size, 1=Decay, 2=Damp, 3=Pre, 4=Width, 5=Mix
//   chorus: 0=Rate, 1=Depth, 2=Voices, 3=Spread, 4=Mix
//   phaser: 0=Rate, 1=Depth, 2=Stages, 3=Feedback, 4=Mix
//   flanger: 0=Rate, 1=Depth, 2=Feedback, 3=Mix
//   comp: 0=Thresh, 1=Ratio, 2=Attack, 3=Release, 4=Makeup
//   limiter: 0=Ceiling, 1=Release
//   tape: 0=Wow, 1=Flutter, 2=Sat, 3=Hiss, 4=Mix
//   grain: 0=Size, 1=Spray, 2=Pitch, 3=Density, 4=Mix
//   ring: 0=Pitch, 1=Decay, 2=Tone, 3=Mix
//   width: 0=Width, 1=Pan, 2=Bass mono
//   fxchain: 0=Chorus, 1=Delay, 2=Reverb, 3=Mix
//   patch: 0=Depth, 1=Slew
//   macros: 0=M1, 1=M2, 2=M3, 3=M4
//   mixer: 0=A, 1=B, 2=C, 3=D
//   voice: 0=Mode, 1=Unison, 2=Detune, 3=Spread, 4=Glide
//   split: 0=Freq, 1=Slope, 2=Balance
//   out: 0=Level
//   screen: 0=Mode, 1=Rate, 2=Tilt, 3=Decay
//   scope: 0=Time, 1=Gain, 2=Trace
//   analyser: 0=Bands, 1=Tilt, 2=Smooth
//   meter: 0=Hold
//   keys: 0=Range
//   xy: 0=Grid
//   pads: 0=Cols, 1=Rows
//   readout: 0=Source, 1=Rate

namespace aka::dsp
{

enum class BlockType
{
    none         =  0,
    osc          =  1,  // Oscillator
    sub          =  2,  // Sub
    noise        =  3,  // Noise
    wavetable    =  4,  // Wavetable
    sampler      =  5,  // Sampler
    fmop         =  6,  // FM operator
    string       =  7,  // String
    filter       =  8,  // Filter
    formant      =  9,  // Formant
    comb         = 10,  // Comb
    drive        = 11,  // Character
    fold         = 12,  // Wavefolder
    crush        = 13,  // Bitcrusher
    eq           = 14,  // EQ
    gate         = 15,  // Gate
    env          = 16,  // Envelope
    env2         = 17,  // Mod envelope
    lfo          = 18,  // LFO
    random       = 19,  // Random
    follow       = 20,  // Follower
    seq          = 21,  // Sequencer
    arp          = 22,  // Arpeggiator
    keytrack     = 23,  // Key tracking
    delay        = 24,  // Delay
    reverb       = 25,  // Reverb
    chorus       = 26,  // Chorus
    phaser       = 27,  // Phaser
    flanger      = 28,  // Flanger
    comp         = 29,  // Compressor
    limiter      = 30,  // Limiter
    tape         = 31,  // Tape
    grain        = 32,  // Granular
    ring         = 33,  // Resonator
    width        = 34,  // Stereo
    fxchain      = 35,  // FX chain
    patch        = 36,  // Patch bay
    macros       = 37,  // Macros
    mixer        = 38,  // Mixer
    voice        = 39,  // Voice
    split        = 40,  // Crossover
    out          = 41,  // Output
    screen       = 42,  // Screen
    scope        = 43,  // Scope
    analyser     = 44,  // Analyser
    meter        = 45,  // Meter
    keys         = 46,  // Keyboard
    xy           = 47,  // XY pad
    pads         = 48,  // Pads
    readout      = 49,  // Readout
    numTypes
};

struct BlockInfo
{
    const char* id;
    const char* name;
    /** True if the block belongs to a voice; false if it runs on the sum. */
    bool voiceStage;
    int numParams;
};

inline constexpr BlockInfo blockInfo[] = {
    { "none", "None", false,  0 },
    { "osc", "Oscillator", true ,  5 },  // osc
    { "sub", "Sub", true ,  3 },  // sub
    { "noise", "Noise", true ,  3 },  // noise
    { "wavetable", "Wavetable", true ,  4 },  // wavetable
    { "sampler", "Sampler", true ,  5 },  // sampler
    { "fmop", "FM operator", true ,  4 },  // fmop
    { "string", "String", true ,  4 },  // string
    { "filter", "Filter", true ,  5 },  // filter
    { "formant", "Formant", true ,  4 },  // formant
    { "comb", "Comb", true ,  3 },  // comb
    { "drive", "Character", true ,  4 },  // drive
    { "fold", "Wavefolder", true ,  3 },  // fold
    { "crush", "Bitcrusher", true ,  4 },  // crush
    { "eq", "EQ", true ,  4 },  // eq
    { "gate", "Gate", true ,  4 },  // gate
    { "env", "Envelope", true ,  6 },  // env
    { "env2", "Mod envelope", true ,  7 },  // env2
    { "lfo", "LFO", true ,  4 },  // lfo
    { "random", "Random", true ,  4 },  // random
    { "follow", "Follower", true ,  3 },  // follow
    { "seq", "Sequencer", true ,  4 },  // seq
    { "arp", "Arpeggiator", true ,  4 },  // arp
    { "keytrack", "Key tracking", true ,  3 },  // keytrack
    { "delay", "Delay", false,  6 },  // delay
    { "reverb", "Reverb", false,  6 },  // reverb
    { "chorus", "Chorus", false,  5 },  // chorus
    { "phaser", "Phaser", false,  5 },  // phaser
    { "flanger", "Flanger", false,  4 },  // flanger
    { "comp", "Compressor", false,  5 },  // comp
    { "limiter", "Limiter", false,  2 },  // limiter
    { "tape", "Tape", false,  5 },  // tape
    { "grain", "Granular", false,  5 },  // grain
    { "ring", "Resonator", false,  4 },  // ring
    { "width", "Stereo", false,  3 },  // width
    { "fxchain", "FX chain", false,  4 },  // fxchain
    { "patch", "Patch bay", false,  2 },  // patch
    { "macros", "Macros", false,  4 },  // macros
    { "mixer", "Mixer", false,  4 },  // mixer
    { "voice", "Voice", false,  5 },  // voice
    { "split", "Crossover", false,  3 },  // split
    { "out", "Output", false,  1 },  // out
    { "screen", "Screen", false,  4 },  // screen
    { "scope", "Scope", false,  3 },  // scope
    { "analyser", "Analyser", false,  3 },  // analyser
    { "meter", "Meter", false,  1 },  // meter
    { "keys", "Keyboard", false,  1 },  // keys
    { "xy", "XY pad", false,  1 },  // xy
    { "pads", "Pads", false,  2 },  // pads
    { "readout", "Readout", false,  2 },  // readout
};

inline constexpr int numBlockTypes = (int) BlockType::numTypes;

inline constexpr BlockInfo info (BlockType t)
{
    const int i = (int) t;
    return (i >= 0 && i < numBlockTypes) ? blockInfo[i] : blockInfo[0];
}

inline constexpr bool isVoiceBlock (BlockType t) { return info (t).voiceStage; }

} // namespace aka::dsp
