#pragma once

// GENERATED by web/scripts/sync-design-tokens.mts — do not edit.
// Source of truth: web/src/design/tokens.ts. Run `pnpm sync:tokens` in web/.
//
// Same palette the website ships, mapped into the vocabulary the plugins use.
// Alpha-over-surface tokens are composited against the surface they sit on at
// generation time, because C++ needs an opaque ARGB word where CSS can defer
// the blend to paint time.

#include <juce_core/juce_core.h>

namespace aka
{

/** One accent at three strengths: full, knocked back, and a glow. */
struct Accent
{
    juce::uint32 base;
    juce::uint32 soft;
    juce::uint32 glow;
};

enum AccentId { accentBlue = 0, accentGreen, accentAmber, accentRose, accentViolet, numAccents };

/**
    The chassis, plus every accent it can spend.

    A plugin picks one accent and stays with it — that is the house rule the
    site enforces too, where each instrument owns exactly one and spends it on a
    single status dot. `record`, `selected` and `active` are the exceptions:
    they are state, not identity, and are the same colour in every plugin.
*/
struct Theme
{
    const char* name;

    juce::uint32 bgDeep;
    juce::uint32 bgPanel;
    juce::uint32 bgScreen;
    juce::uint32 divider;
    juce::uint32 trackDim;

    juce::uint32 textDim;
    juce::uint32 textMid;
    juce::uint32 textHi;
    juce::uint32 textOnAccent;

    // State, not identity. These mean the same thing in every instrument and
    // are the same colour in all of them, so transport muscle memory survives
    // moving between plugins — and survives a theme flip.
    juce::uint32 record;
    juce::uint32 recordSoft;
    juce::uint32 selected;
    juce::uint32 selectedSft;
    juce::uint32 active;
    juce::uint32 activeSoft;

    Accent accents[numAccents];

    const char* monoFontName;
};

inline constexpr Theme themes[] = {
    {
        "warm near-black",
        0xff0a0a09, 0xff111110, 0xff020201,
        0xff292928, 0xff181817,
        0xff898987, 0xffb8b9b6, 0xffeaeae8, 0xff0c0c0b,
        0xffec7380, 0xff733d42, 0xfff0be67, 0xff755f37, 0xff69b57f, 0xff395b42,
        {
        { 0xff5d98f4, 0xff334d76, 0xff1e2939 }, // blue
        { 0xff69b57f, 0xff395b42, 0xff212e24 }, // green
        { 0xfff0be67, 0xff755f37, 0xff39301f }, // amber
        { 0xffec7380, 0xff733d42, 0xff382224 }, // rose
        { 0xffb3a0ec, 0xff5a5173, 0xff2e2a37 }, // violet
        },
        "Menlo"
    },
    {
        "warm paper",
        0xfff0f0ee, 0xfffdfdfb, 0xffdededb,
        0xffdcdcdb, 0xffe6e6e4,
        0xff5e5e5b, 0xff333331, 0xff0d0d0c, 0xfffafaf9,
        0xffbd1f44, 0xffe099a9, 0xff8b5f14, 0xffc9b693, 0xff197d42, 0xff96c3a8,
        {
        { 0xff1362d2, 0xff93b7e9, 0xffd3e1f4 }, // blue
        { 0xff197d42, 0xff96c3a8, 0xffd4e6da }, // green
        { 0xff8b5f14, 0xffc9b693, 0xffe8e0d2 }, // amber
        { 0xffbd1f44, 0xffe099a9, 0xfff1d5da }, // rose
        { 0xff7447c8, 0xffbfabe4, 0xffe4dcf2 }, // violet
        },
        "Menlo"
    },
};

inline constexpr int themeCount = (int) (sizeof (themes) / sizeof (themes[0]));

} // namespace aka
